### ISSUE TITLE
iPhone XS/XS Max/XR implementation

### ISSUE THREAD

**Issue by agreensh** [ominibyte/flutter_device_type#1]
What about tests for iPhone XS, iPhone XS Max, iPhone XR?
Currently, isIphoneX will return false for XS, XS Max and XR.

**Comment by ominibyte** [comment]
Thanks for detecting this. I will look into this as soon as I can. However, if you have a solution you can submit a PR.

**Comment by g-balas** [comment]
Definitly a deal breaker...

**Comment by ominibyte** [comment]
This should be resolved in the new code base. I've updated the version on pub to 0.2.0
