### ISSUE TITLE
[Suggestion] Change isiPhoneX to something more generic

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [ominibyte/flutter_device_type#4]
I would suggest `hasNotch` or something like that so you don't have to make new methods for the same type of check

**Comment by leogouveia** [comment]
Just made a Pull Request #5 with requested feature =)

**Comment by ThinkDigitalSoftware** [comment]
Thanks!

**Comment by ominibyte** [comment]
Closing cause feature has been implemented.
