### ISSUE TITLE
Detection is not accurate.

### ISSUE THREAD

**Issue by MojtabaTavakkoli** [ominibyte/flutter_device_type#7]
It detects Samsung Galaxy A20 as a tablet for instance.

**Comment by aanorbel** [comment]
Yes I have noticed this too. One of my testers reported this.

**Comment by 7Kronos** [comment]
Great work !
Just reporting that Galaxy S20 is also detected as a tablet !

**Comment by ominibyte** [comment]
Work has been done to improve detection in version 0.3.0
